name: 'UI Library projects CI'

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.runs-on }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

    # Install Node version
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

    # Install dependencies for project
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          # don't treat warning as failures
          CI: ""
        run: npm install
        
    # Build project
      - name: Build
        working-directory: ${{ inputs.working-directory }}
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          # don't treat warning as failures
          CI: ""
        run: npm run build
