name: '1-on-1 voice calling CI'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main in specific path.
  push:
    paths:
      - 'add-1-on-1-voice-calling/**'

  pull_request:
    paths:
      - 'add-1-on-1-voice-calling/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_add-1-on-1-voice-calling"
  build_add-1-on-1-voice-calling:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Install Node version v18.x
      - name: Use Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

    # Install dependencies on "add-1-on-1-voice-calling"
      - name: Install dependencies
        working-directory: ./add-1-on-1-voice-calling
        run: npm install
        
    # Build "add-1-on-1-voice-calling"
      - name: Build "add-1-on-1-voice-calling"
        working-directory: ./add-1-on-1-voice-calling
        run: npx webpack --config webpack.config.js
