name: 'ui-library-add-call-recording CI'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main in specific path.
  push:
    paths:
      - 'ui-library-add-call-recording/app/**'
  pull_request:
    paths:
      - 'ui-library-add-call-recording/app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  project-validation:
    uses: ./.github/workflows/ci-ui-library.yml
    with:
      runs-on: 'ubuntu-latest'
      node-version: '22.x'
      working-directory: './ui-library-add-call-recording/app'